import type { BriefTemplate } from "./types";

export const BRIEF_TEMPLATES: Record<string, BriefTemplate> = {
  monday_morning: {
    id: "monday_morning",
    title: "Monday Morning Brief",
    subtitle: "Your weekly exec summary",
    description: "A 5-section narrative of last week — what worked, what broke, what to watch.",
    icon: "Calendar",
    estimatedSeconds: 75,
    agents: ["maya", "arjun", "priya", "kabir", "raavi"],
  },
  bleeding_money: {
    id: "bleeding_money",
    title: "Where I'm Bleeding Money",
    subtitle: "Paid sources that flop",
    description: "Maya audits every paid channel against the organic baseline and names the underperformers.",
    icon: "Wallet",
    estimatedSeconds: 60,
    agents: ["maya"],
  },
  landing_pages: {
    id: "landing_pages",
    title: "The Real Landing Page Report",
    subtitle: "The report GA4 took away from us",
    description: "Top 30 landing pages with sessions, engagement, conversions and source — sortable + exportable.",
    icon: "FileText",
    estimatedSeconds: 45,
    agents: ["arjun"],
  },
  find_whales: {
    id: "find_whales",
    title: "Find My Whales",
    subtitle: "Who buys? Where to find more.",
    description: "Priya + Kabir profile the highest-converting cohort and pitch where to acquire more of them.",
    icon: "Users",
    estimatedSeconds: 70,
    agents: ["priya", "kabir"],
  },
  funnel_forensics: {
    id: "funnel_forensics",
    title: "Funnel Forensics",
    subtitle: "Where the conversion flow bleeds",
    description: "Arjun auto-detects your funnel from real events and pinpoints the worst drop.",
    icon: "TrendingDown",
    estimatedSeconds: 65,
    agents: ["arjun"],
  },
  time_travel: {
    id: "time_travel",
    title: "Time-Travel Comparison",
    subtitle: "Compare any two periods",
    description: "Side-by-side KPIs and biggest movers across two date ranges you choose.",
    icon: "History",
    needsInput: true,
    estimatedSeconds: 80,
    agents: ["maya", "arjun", "priya", "kabir", "raavi"],
  },
  hidden_segments: {
    id: "hidden_segments",
    title: "Hidden Segments",
    subtitle: "Simpson's paradox in your data",
    description: "Kabir + Raavi surface segments quietly winning and quietly losing under your aggregate numbers.",
    icon: "Eye",
    estimatedSeconds: 70,
    agents: ["kabir", "raavi"],
  },
  anomaly_hunter: {
    id: "anomaly_hunter",
    title: "The Anomaly Hunter",
    subtitle: "What changed this week",
    description: "Raavi runs statistical anomaly detection against a 4-week baseline and surfaces the material moves.",
    icon: "AlertTriangle",
    estimatedSeconds: 60,
    agents: ["raavi"],
  },
  zombie_pages: {
    id: "zombie_pages",
    title: "Zombie Pages",
    subtitle: "Kill / redirect / improve",
    description: "Classify every page with >100 sessions into Healthy, Underperforming, or Zombie.",
    icon: "Skull",
    estimatedSeconds: 55,
    agents: ["arjun"],
  },
  todo_list: {
    id: "todo_list",
    title: "Tomorrow's To-Do List",
    subtitle: "5 actions for this week",
    description: "Five specific, time-bound, owner-tagged actions distilled from your latest findings.",
    icon: "ListChecks",
    estimatedSeconds: 50,
    agents: ["maya", "arjun", "priya", "kabir", "raavi"],
  },
  channel_mix_health: {
    id: "channel_mix_health",
    title: "Channel Mix Health",
    subtitle: "Where every session actually came from",
    description:
      "Velir's default-channel-grouping classifier applied to source/medium/campaign. Shows share, week-over-week delta, and conversion rate per channel.",
    icon: "Network",
    estimatedSeconds: 50,
    agents: ["maya"],
  },
  funnel_health: {
    id: "funnel_health",
    title: "Funnel Health",
    subtitle: "Step-by-step user counts and drop-offs",
    description:
      "Real GA4 funnel report (D2C or B2B template auto-detected) with active-users per step, next-step rate, and the worst-leaking transition.",
    icon: "GitBranch",
    estimatedSeconds: 55,
    agents: ["arjun"],
  },
  attribution_comparison: {
    id: "attribution_comparison",
    title: "Attribution Comparison",
    subtitle: "First-click vs last-click — who's stealing credit",
    description:
      "Side-by-side first-user channel vs session channel for the same conversions. Surfaces over-credited and under-credited channels.",
    icon: "Scale",
    estimatedSeconds: 55,
    agents: ["maya", "kabir"],
  },
  cohort_retention: {
    id: "cohort_retention",
    title: "Cohort Retention",
    subtitle: "Weekly acquisition cohorts, 8 weeks",
    description:
      "GA4 cohort report on weekly acquisition cohorts, charting retention week-by-week. Surfaces the fastest churners and stickiest cohorts.",
    icon: "LineChart",
    estimatedSeconds: 50,
    agents: ["raavi"],
  },
  landing_page_health: {
    id: "landing_page_health",
    title: "Landing Page Health",
    subtitle: "Best and worst pages by conversion rate",
    description:
      "Top 10 and bottom 10 landing pages by conversion rate (with minimum traffic threshold) — for each, sessions, engagement rate, and bounce rate.",
    icon: "Layout",
    estimatedSeconds: 45,
    agents: ["arjun"],
  },
  weekly_paid_marketing: {
    id: "weekly_paid_marketing",
    title: "Weekly Performance Marketing",
    subtitle: "Vera's roll-up of last week's paid",
    description:
      "Total spend, top movers, what's scaling, what's bleeding, and recommended budget shifts for next week — joined to GA4 reality.",
    icon: "Wallet",
    estimatedSeconds: 65,
    agents: ["vera"],
  },
  wasted_spend_audit: {
    id: "wasted_spend_audit",
    title: "Wasted Spend Audit",
    subtitle: "Negative keywords + ad pauses, ready to paste",
    description:
      "Search terms with >100 clicks and zero conversions, plus underperforming ad variants. Copy-paste list for your next optimization ticket.",
    icon: "Skull",
    estimatedSeconds: 55,
    agents: ["vera"],
  },
};

export const BRIEF_ORDER: string[] = [
  "monday_morning",
  "weekly_paid_marketing",
  "wasted_spend_audit",
  "channel_mix_health",
  "funnel_health",
  "attribution_comparison",
  "cohort_retention",
  "landing_page_health",
  "bleeding_money",
  "landing_pages",
  "find_whales",
  "funnel_forensics",
  "time_travel",
  "hidden_segments",
  "anomaly_hunter",
  "zombie_pages",
  "todo_list",
];
