#!/usr/bin/env python3
"""Generate a curated, GA4-only brief library replacing the bloated seed.
Run from project root: python3 scripts/gen-ga-library.py"""

import json
from datetime import datetime

NOW = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def brief(
    *,
    id_,
    name,
    one_line,
    long_desc,
    funnel,
    persona,
    schedule="weekly",
    complexity="basic",
    is_popular=False,
    is_new=False,
    roles=None,
    metrics=None,
    dimensions=None,
    collections=None,
    read_minutes=4,
):
    slug = id_.replace("brief-ga-", "")
    return {
        "id": id_,
        "name": name,
        "slug": slug + "-v1",
        "version": "1.0.0",
        "status": "published",
        "industry": {"primary": "all", "secondary": [], "is_universal": True},
        "use_case_tags": [],
        "one_line_summary": one_line,
        "detailed_description": long_desc,
        "metrics": [
            {"name": m, "type": "numeric", "description": ""} for m in (metrics or [])
        ],
        "dimensions": [
            {"name": d, "type": "string", "description": ""} for d in (dimensions or [])
        ],
        "data_sources": ["ga4"],
        "funnel_stage": funnel,
        "secondary_funnel_stages": [],
        "roles": roles or ["growth_marketer", "founder", "cmo"],
        "schedule": schedule,
        "complexity": complexity,
        "agent_persona": persona,
        "estimated_read_time_minutes": read_minutes,
        "collections": collections or ["marketing-essentials"],
        "is_popular": is_popular,
        "is_new": is_new,
        "customization_required": False,
        "geo": "global",
        "created_at": NOW,
        "updated_at": NOW,
    }


BRIEFS = [
    # ── Acquisition (5) ─────────────────────────────────────────────────────
    brief(
        id_="brief-ga-channel-mix-this-week",
        name="Channel Mix This Week",
        one_line="Where did traffic come from this week vs last? Channel-by-channel WoW with the biggest movers flagged.",
        long_desc="Pulls sessions, users, conversions and conversion rate split by `sessionDefaultChannelGroup` for the last 7 days and the prior 7 days. Ranks channels by absolute change, highlights the top three gainers and top three decliners, and includes a 1-line interpretation per movement (e.g. 'Paid social fell 18% week-over-week — check if a campaign paused'). Use this every Monday morning to know where last week's wins and losses landed before anyone asks.",
        funnel="acquisition",
        persona="maya",
        schedule="weekly",
        is_popular=True,
        metrics=["sessions", "totalUsers", "keyEvents", "conversionRate"],
        dimensions=["sessionDefaultChannelGroup"],
        collections=["marketing-essentials", "weekly-rituals"],
    ),
    brief(
        id_="brief-ga-top-converting-sources",
        name="Top Converting Sources",
        one_line="Which exact source/medium combos punch above their weight on conversions, not just sessions.",
        long_desc="Beyond channel-level rollups — this drills into `sessionSource` × `sessionMedium` and ranks each pair by conversions per session. Flags pairs with low traffic but high conversion (hidden gems worth scaling) and high traffic but low conversion (likely wasted attention). Includes a 'budget-shift suggestion' line per row.",
        funnel="acquisition",
        persona="maya",
        is_popular=True,
        metrics=["sessions", "keyEvents", "conversionRate"],
        dimensions=["sessionSource", "sessionMedium"],
    ),
    brief(
        id_="brief-ga-new-traffic-discovery",
        name="New Traffic Discovery",
        one_line="Sources that appeared this week but weren't there last week — fresh attention you didn't know you had.",
        long_desc="Diffs `sessionSource` / `sessionMedium` over the last 7 days vs the prior 7 days. Flags every source/medium combo with zero sessions in the prior period and meaningful sessions now. Often catches viral mentions, sudden referral spikes, or campaigns from teammates you didn't know launched.",
        funnel="acquisition",
        persona="maya",
        complexity="intermediate",
        metrics=["sessions", "totalUsers"],
        dimensions=["sessionSource", "sessionMedium"],
    ),
    brief(
        id_="brief-ga-brand-vs-non-brand",
        name="Brand vs Non-Brand Split",
        one_line="How much of organic search demand is people typing your brand name vs discovering you via category queries.",
        long_desc="Splits organic search traffic into branded (queries containing your brand name) vs non-branded (everything else). Trends both lines for the last 12 weeks. A healthy SaaS or D2C brand wants non-brand growing — pure brand growth is just demand that already exists. We surface the ratio + the trend, plus the biggest non-brand pages by entrance.",
        funnel="acquisition",
        persona="maya",
        complexity="intermediate",
        metrics=["sessions", "totalUsers"],
        dimensions=["landingPagePlusQueryString", "sessionSource"],
    ),
    brief(
        id_="brief-ga-paid-vs-organic-vs-direct",
        name="Paid vs Organic vs Direct vs Referral",
        one_line="The four-bucket split: who's paying their way, who's earned, who's free, who's borrowed.",
        long_desc="A simple 4-bucket macro view: Paid Search + Paid Social grouped as 'Paid', Organic Search + Organic Social as 'Organic', Direct as 'Direct', Referral + Email as 'Earned/Referral'. Compares share-of-sessions and share-of-conversions across the four. The gap between the two shares (e.g. paid = 35% of sessions but 12% of conversions) is the headline insight.",
        funnel="acquisition",
        persona="maya",
        is_popular=True,
        metrics=["sessions", "keyEvents"],
        dimensions=["sessionDefaultChannelGroup"],
    ),
    # ── Behavior / Content (5) ──────────────────────────────────────────────
    brief(
        id_="brief-ga-top-landing-pages",
        name="Top Landing Pages",
        one_line="The pages doing the heavy lifting at the entrance — sessions in, sessions kept, sessions converted.",
        long_desc="Top 20 landing pages by sessions, with engagement rate, bounce rate, average engagement time, and conversion rate next to each. Flags pages where lots of people land but few engage, and pages with surprisingly high conversion per session that may be under-promoted.",
        funnel="acquisition",
        persona="arjun",
        is_popular=True,
        metrics=["sessions", "engagementRate", "bounceRate", "conversionRate"],
        dimensions=["landingPage"],
    ),
    brief(
        id_="brief-ga-high-bounce-leaders",
        name="High Bounce Pages",
        one_line="Where people land, scan, and bail. Sorted by absolute bounce volume so you fix the ones that actually move the needle.",
        long_desc="Pages ranked not by bounce rate alone but by (bounce rate × landings) — the absolute count of bouncing sessions. Fixing a 90% bounce on a page with 50 sessions doesn't matter; a 65% bounce on a page with 8,000 sessions is the real lever. Bottom rule of thumb: bounce above category benchmark + meaningful volume = an investigation target.",
        funnel="engagement",
        persona="arjun",
        metrics=["sessions", "bounceRate"],
        dimensions=["pagePath"],
    ),
    brief(
        id_="brief-ga-engagement-leaders-laggards",
        name="Engagement Leaders & Laggards",
        one_line="Best- and worst-engaged pages by avg engagement time — what holds attention and what burns it.",
        long_desc="Sorts pages by average engagement time per session. The top 10 are likely your high-trust content; the bottom 10 might be broken navigation, slow pages, or content with wrong intent for the traffic landing on it. Pairs each row with sessions so you can prioritise volume × delta.",
        funnel="engagement",
        persona="arjun",
        metrics=["userEngagementDuration", "sessions"],
        dimensions=["pagePath"],
    ),
    brief(
        id_="brief-ga-site-search-insights",
        name="Site Search Insights",
        one_line="What people search for ONCE they're already on your site — the gap between what you sell and what they want.",
        long_desc="Aggregates GA4 search-term events (or your custom search-query dimension if configured). Surfaces the top 20 queries, queries with zero results, and queries whose result-click-through is low. Each surfaced query is a direct read on user intent your nav/IA isn't covering.",
        funnel="engagement",
        persona="arjun",
        complexity="intermediate",
        metrics=["eventCount"],
        dimensions=["searchTerm"],
    ),
    brief(
        id_="brief-ga-page-to-page-flow",
        name="Top Page-to-Page Paths",
        one_line="The most-trafficked next-step paths on your site — your real user flow vs the one you designed.",
        long_desc="Looks at sequential `page_view` events to surface the most common (previousPage → currentPage) pairs. Often surprising: people don't go where the nav suggests; they go where they're curious. This brief highlights the top 15 actual paths, flags any path with conversion attached, and shows where your designed flow breaks.",
        funnel="engagement",
        persona="arjun",
        complexity="advanced",
        metrics=["sessions"],
        dimensions=["pageReferrer", "pagePath"],
    ),
    # ── Audience (4) ────────────────────────────────────────────────────────
    brief(
        id_="brief-ga-audience-snapshot",
        name="Audience Snapshot",
        one_line="Who's actually visiting you right now — age, gender, country, device — in one screen.",
        long_desc="A single canvas with the four classic audience cuts: age band, gender split, top 10 countries, device category (mobile/desktop/tablet). Each cut shows the audience % and the conversion-rate % side-by-side, so you see not just who shows up but who actually buys.",
        funnel="audience",
        persona="kabir",
        is_popular=True,
        metrics=["totalUsers", "conversionRate"],
        dimensions=["userAgeBracket", "userGender", "country", "deviceCategory"],
    ),
    brief(
        id_="brief-ga-new-vs-returning-health",
        name="New vs Returning Health",
        one_line="The retention barometer for any business — is the returning-user line trending up or down?",
        long_desc="Plots new vs returning users week-over-week for the last 13 weeks. A healthy product-led business sees returning grow as a share over time. A pure ad-driven D2C will often see new dominate. We surface the ratio + recommend the next move based on direction: if returning is shrinking, content/email focus; if new is shrinking, acquisition focus.",
        funnel="retention",
        persona="priya",
        is_popular=True,
        metrics=["totalUsers", "newUsers"],
        dimensions=["date"],
    ),
    brief(
        id_="brief-ga-geo-concentration",
        name="Geo Concentration",
        one_line="What share of your traffic + revenue comes from your top 5 cities/countries — and where you have room.",
        long_desc="Shows the cumulative share-of-conversions for the top 5, top 10, and top 20 locations. If your top 5 cities are 80%+ of conversions, you have a concentration risk (or a clear expansion opportunity). Includes a 'underexposed regions' list — places with reasonable session share but low conversion share that might just need localised content.",
        funnel="audience",
        persona="kabir",
        metrics=["sessions", "keyEvents"],
        dimensions=["country", "region", "city"],
    ),
    brief(
        id_="brief-ga-mobile-vs-desktop",
        name="Mobile vs Desktop Gap",
        one_line="Where the mobile experience is leaving money on the table compared to desktop.",
        long_desc="For each top source, shows mobile vs desktop conversion rate side-by-side. The biggest gap is your highest-leverage UX fix. Often mobile-paid-search converts at half the rate of desktop-organic — a finding directly worth budget reallocation.",
        funnel="conversion",
        persona="priya",
        is_popular=True,
        metrics=["sessions", "conversionRate"],
        dimensions=["deviceCategory", "sessionDefaultChannelGroup"],
    ),
    # ── Conversion (5) ──────────────────────────────────────────────────────
    brief(
        id_="brief-ga-conversion-rate-trend",
        name="Conversion Rate Trend",
        one_line="The single most-asked-about number in your business: is conversion going up or down?",
        long_desc="Plots overall conversion rate week-over-week for the last 13 weeks. Highlights any week with a >5% absolute swing. Decomposes any movement into source mix change, device mix change, or true rate change — so you can tell 'fewer converters' from 'different audience showed up'.",
        funnel="conversion",
        persona="arjun",
        is_popular=True,
        metrics=["sessions", "keyEvents", "conversionRate"],
        dimensions=["date"],
    ),
    brief(
        id_="brief-ga-funnel-breakdown",
        name="Auto-Detected Funnel",
        one_line="Your most-fired event sequence with drop-off at each step — without setting up funnels in GA UI.",
        long_desc="Inspects which events fire most for your property — typically `view_item → add_to_cart → begin_checkout → purchase` for D2C, or `page_view → form_start → form_submit → generate_lead` for B2B. Computes step-to-step drop-off percentages and flags the worst step. No GA4 funnel config required — we auto-detect from data.",
        funnel="conversion",
        persona="arjun",
        is_popular=True,
        complexity="intermediate",
        metrics=["eventCount", "totalUsers"],
        dimensions=["eventName"],
    ),
    brief(
        id_="brief-ga-conversion-by-channel",
        name="Conversion Rate by Channel",
        one_line="Which channels actually convert vs which just bring tyre-kickers.",
        long_desc="Conversion rate per `sessionDefaultChannelGroup` over the last 28 days, with the absolute conversions count beside the rate. A channel with a 1.5% rate doesn't matter if it brings 50,000 sessions; a 6% rate doesn't matter if it brings 200. We force you to look at both.",
        funnel="conversion",
        persona="arjun",
        is_popular=True,
        metrics=["sessions", "keyEvents", "conversionRate"],
        dimensions=["sessionDefaultChannelGroup"],
    ),
    brief(
        id_="brief-ga-revenue-per-session",
        name="Revenue per Session Trend",
        one_line="The money-velocity metric — is each session worth more or less than it was?",
        long_desc="If you have GA4 e-commerce tracking, this trends `totalRevenue / sessions` week-over-week. The number falling means traffic quality is dropping (more lookers, fewer buyers, or smaller orders); rising means you're either getting better traffic or improving AOV. Includes a split by channel so you can see which sources are getting more valuable.",
        funnel="revenue",
        persona="vera",
        complexity="intermediate",
        metrics=["totalRevenue", "sessions"],
        dimensions=["date", "sessionDefaultChannelGroup"],
    ),
    brief(
        id_="brief-ga-top-converting-content",
        name="Top Converting Content",
        one_line="Pages that punch above their weight on conversion — the content team's reusable insight.",
        long_desc="Ranks pages by conversion-rate-per-session, filtered to pages with at least 100 sessions in the period. The list often surprises: a deep blog post or a comparison page tends to outperform the homepage on per-session conversion. Each row gets a 'why this works' hypothesis from Arjun.",
        funnel="conversion",
        persona="arjun",
        metrics=["sessions", "keyEvents", "conversionRate"],
        dimensions=["pagePath"],
    ),
    # ── Retention (3) ───────────────────────────────────────────────────────
    brief(
        id_="brief-ga-active-user-series",
        name="Active User Series (DAU/WAU/MAU)",
        one_line="The product-engagement vital signs — daily, weekly, and monthly active users on one chart.",
        long_desc="Plots 1-day, 7-day, and 28-day active users on the same axis. Two key ratios fall out: DAU/MAU (stickiness — 20%+ is great), and WAU/MAU (weekly engagement). Surfaces any divergence between weekly and 28-day — for example flat WAU + falling 28-day means you're losing the casual edge of your audience.",
        funnel="retention",
        persona="priya",
        is_popular=True,
        metrics=["active1DayUsers", "active7DayUsers", "active28DayUsers"],
        dimensions=["date"],
    ),
    brief(
        id_="brief-ga-weekly-cohorts",
        name="Weekly Cohort Retention",
        one_line="The retention heatmap. Are recent weeks of acquired users sticking better or worse than older weeks?",
        long_desc="Uses GA4's `cohortSpec` to plot 8 weekly cohorts × 8 retention weeks. A healthy cohort shape: each new cohort retains as well or better than the prior one. A bad shape: each cohort drops off faster — often a sign your acquisition is getting lower-quality. Includes a one-line read of whether the trend is improving or decaying.",
        funnel="retention",
        persona="priya",
        is_popular=True,
        complexity="advanced",
        metrics=["cohortActiveUsers"],
        dimensions=["cohort", "cohortNthWeek"],
    ),
    brief(
        id_="brief-ga-returner-source-quality",
        name="Returner Source Quality",
        one_line="Which acquisition channel actually brings users who come back? Sessions are easy. Returns are real.",
        long_desc="For each `sessionDefaultChannelGroup`, compares new-user count this period vs return-user count from the same source in the next period. A high return-rate channel is gold — those users found you once and chose to come back. We rank channels by 14-day return rate and flag the surprises.",
        funnel="retention",
        persona="priya",
        complexity="intermediate",
        metrics=["totalUsers", "newUsers"],
        dimensions=["sessionDefaultChannelGroup"],
    ),
    # ── Most-valuable-users briefs (the WOW set) ────────────────────────────
    brief(
        id_="brief-ga-power-user-profile",
        name="Power User Profile",
        one_line="Who are your top 25% of users by engagement? The demographic, geographic, and device profile of the people who actually love your product.",
        long_desc="Splits your user base into engagement-time quartiles and zooms in on the top quartile. For that cohort: top 5 cities, age-band split, gender split, device split, top 5 traffic sources, top 5 landing pages, and conversion rate. Each cut is contrasted against the bottom quartile so the differences pop. A typical surprise: 'Your power users are 80% mobile but your messaging assumes desktop' or 'Power users come from 3 cities you don't run ads in.' This is the closest GA4 will get you to an ICP without a CRM.",
        funnel="audience",
        persona="kabir",
        is_popular=True,
        is_new=True,
        complexity="advanced",
        metrics=["userEngagementDuration", "totalUsers", "keyEvents", "conversionRate"],
        dimensions=[
            "city",
            "country",
            "userAgeBracket",
            "userGender",
            "deviceCategory",
            "sessionDefaultChannelGroup",
        ],
        collections=["wow-insights", "audience-essentials"],
        read_minutes=6,
    ),
    brief(
        id_="brief-ga-gateway-pages",
        name="Gateway Pages",
        one_line="Landing pages ranked by the QUALITY of the user they bring in — not by session count. The pages that punch above their weight.",
        long_desc="For each landing page, computes: avg engagement time of users who landed there, their 7-day return rate, and their downstream conversion rate. Surfaces pages whose visitors stay longer, return sooner, and convert better — regardless of how big the page's session count is. The result regularly shocks marketers: a long-form blog post or a comparison page beats the homepage on per-user value. Each row gets a recommendation: 'amplify with paid', 'add to nav', 'feature in email'.",
        funnel="acquisition",
        persona="arjun",
        is_popular=True,
        is_new=True,
        complexity="advanced",
        metrics=["sessions", "userEngagementDuration", "conversionRate"],
        dimensions=["landingPage"],
        collections=["wow-insights"],
        read_minutes=5,
    ),
    brief(
        id_="brief-ga-quality-weighted-sources",
        name="Quality-Weighted Source Ranking",
        one_line="Sources scored not by volume but by (engagement × conversion × return rate). The traffic that earned its keep.",
        long_desc="Most channel reports rank by sessions. This one ranks by a quality score: avg engagement seconds × conversion rate × 7-day return rate, all normalised. A source bringing 500 sessions at 4-min engagement and 6% conversion beats a source bringing 50,000 sessions at 25-second engagement and 0.3% conversion. The output is a one-page ranking with the headline gap (e.g. 'Paid Social is your #1 by sessions but #6 by quality — half your spend goes to lower-value attention than Organic Search'). Includes a budget-shift recommendation per surprise.",
        funnel="acquisition",
        persona="maya",
        is_popular=True,
        is_new=True,
        complexity="advanced",
        metrics=["sessions", "userEngagementDuration", "keyEvents", "totalUsers"],
        dimensions=["sessionSource", "sessionMedium", "sessionDefaultChannelGroup"],
        collections=["wow-insights"],
        read_minutes=5,
    ),
    brief(
        id_="brief-ga-activation-path",
        name="The Activation Path",
        one_line="The page sequences shared by users who convert — and the ones unique to users who bounce. The user-journey truth your funnel diagram is hiding.",
        long_desc="Compares the top 10 most-common page sequences (path of 3-4 pages) among CONVERTING users vs NON-converting users for the same period. The intersection is the trivial baseline; the DIFFERENCE is the activation moment — the page or sequence that distinguishes a buyer from a browser. Often surprising: 'converters disproportionately view /pricing AND /case-studies in the same session; non-converters see only one of the two.' That's a UX directive: cross-link them. Output is the top 5 'converter-only paths' with the lift figure.",
        funnel="conversion",
        persona="arjun",
        is_popular=True,
        is_new=True,
        complexity="advanced",
        metrics=["sessions", "keyEvents"],
        dimensions=["pagePath", "pageReferrer"],
        collections=["wow-insights"],
        read_minutes=7,
    ),
    brief(
        id_="brief-ga-time-to-first-value",
        name="Time to First Value",
        one_line="How long does it take a new user to convert? Distribution + splits — so you know whether to retarget at day 1, day 7, or day 30.",
        long_desc="For every converted user in the last 90 days, calculates time-from-first-visit to first conversion + session-count to first conversion. Plots the distribution as a histogram with three buckets: quick converters (same session), warm converters (1-3 sessions, < 7 days), marathon researchers (4+ sessions, > 7 days). Each bucket is profiled — what % are they, what sources/pages/devices dominate each. The output is a concrete retargeting cadence: 'Don't retarget for 24 hours, then hit hard at day 3 and day 7 — that's where 70% of conversions complete.'",
        funnel="conversion",
        persona="priya",
        is_new=True,
        complexity="advanced",
        metrics=["keyEvents", "totalUsers", "sessions"],
        dimensions=["sessionsToConversion", "daysToConversion"],
        collections=["wow-insights", "retargeting-playbook"],
        read_minutes=6,
    ),

    # ── Content intelligence (7) — the drill-downs editorial/SEO teams do manually ──
    brief(
        id_="brief-ga-content-pulse",
        name="Content Pulse",
        one_line="The weekly content briefing: top risers, top fallers, fresh discoveries, decaying classics — in one screen.",
        long_desc="A single composite for anyone running 50+ content pages. Splits your pages into four buckets each Monday morning:\n\n• RISERS — top 5 pages with the biggest week-over-week pageview gains (with the why: 'organic search up 60% for this URL').\n• FALLERS — top 5 with biggest WoW drops (and the proximate cause: lost a referral source, paid campaign ended, ranking dropped).\n• NEWCOMERS — pages with meaningful traffic this week that had zero last week. Often surfaces a new article you forgot you'd published, or an old one Google just rediscovered.\n• DECAYING CLASSICS — 3 pages on a 90-day descending trend. The ones quietly losing audience while you weren't looking — refresh candidates.\n\nEach bucket gets 1 concrete recommendation. This brief replaces the Monday-morning manual click-through of GA4 Pages report.",
        funnel="engagement",
        persona="arjun",
        is_popular=True,
        is_new=True,
        schedule="weekly",
        complexity="advanced",
        roles=["content_marketer", "seo_lead", "editor", "founder"],
        metrics=["screenPageViews", "sessions", "userEngagementDuration"],
        dimensions=["pagePath", "date"],
        collections=["content-intelligence", "weekly-rituals"],
        read_minutes=5,
    ),
    brief(
        id_="brief-ga-content-categories",
        name="Content Categories",
        one_line="Auto-bucket your pages by URL pattern (/blog vs /guides vs /case-studies) and rank each bucket by what actually performs.",
        long_desc="Detects path patterns in your URLs (`/blog/*`, `/guides/*`, `/case-studies/*`, `/help/*`, `/product/*`, etc.) and groups every page into a content category. For each bucket: total sessions, avg engagement time per session, conversion rate, return rate, and share of new-user traffic. The output is a leaderboard that finally answers a question most CMOs can't: 'Are my guides outperforming my blog posts on conversion?' Often surprising — a small bucket like /case-studies/* turns out to be the highest converter per session by 4×.",
        funnel="engagement",
        persona="arjun",
        is_popular=True,
        is_new=True,
        complexity="intermediate",
        roles=["content_marketer", "cmo", "seo_lead", "founder"],
        metrics=["sessions", "userEngagementDuration", "keyEvents", "conversionRate"],
        dimensions=["pagePath"],
        collections=["content-intelligence"],
        read_minutes=4,
    ),
    brief(
        id_="brief-ga-trending-risers",
        name="Trending Content (Risers)",
        one_line="The 10 pages with the biggest WoW pageview gain — and the source that drove each spike.",
        long_desc="For each top riser, decomposes the gain: what % came from organic search, paid, referral, social, direct? When a page jumps 200% in a week, it's usually one channel firing (a tweet, a ranking change, an AI Overview mention). This brief surfaces both the WHAT (which page) and the WHY (which channel) — so you know whether to double-down with paid, lean into the social hook, or fix the source if it's a fluke.",
        funnel="engagement",
        persona="maya",
        is_popular=True,
        is_new=True,
        complexity="intermediate",
        roles=["content_marketer", "seo_lead", "social_media_manager"],
        metrics=["screenPageViews", "sessions"],
        dimensions=["pagePath", "sessionDefaultChannelGroup", "date"],
        collections=["content-intelligence"],
        read_minutes=4,
    ),
    brief(
        id_="brief-ga-decaying-classics",
        name="Decaying Classics",
        one_line="Pages that earned big traffic in the past but have been quietly losing it for 90 days. The refresh queue.",
        long_desc="Identifies pages whose 90-day pageview trend is monotonically declining (or close to it) — pages that used to perform but are sliding. Surfaces the slope of decline, the most likely cause (organic position lost, lost a backlink, content went stale), and a refresh priority score weighted by historical peak. Editorial teams love this brief because it's the closest thing to an 'auto-generated content audit'.",
        funnel="engagement",
        persona="raavi",
        is_new=True,
        complexity="advanced",
        roles=["content_marketer", "seo_lead", "editor"],
        metrics=["screenPageViews", "sessions"],
        dimensions=["pagePath", "date"],
        collections=["content-intelligence"],
        read_minutes=5,
    ),
    brief(
        id_="brief-ga-first-touch-content",
        name="First-Touch Content",
        one_line="The articles people read on their VERY FIRST visit before they eventually converted. Your top-of-funnel champions.",
        long_desc="For every converted user in the last 30 days, finds their FIRST landing page and ranks by which content most often started the conversion journey. Two things pop: (1) the SEO-driven articles bringing real top-of-funnel attention, and (2) the surprise entries — case studies or comparison posts that pull in serious buyers right at first touch. Output includes share-of-conversions attributed to each first-touch page, so you know exactly which content earns budget.",
        funnel="acquisition",
        persona="arjun",
        is_new=True,
        complexity="advanced",
        roles=["content_marketer", "growth_marketer", "cmo"],
        metrics=["sessions", "keyEvents", "totalUsers"],
        dimensions=["landingPage"],
        collections=["content-intelligence", "wow-insights"],
        read_minutes=5,
    ),
    brief(
        id_="brief-ga-engagement-erosion",
        name="Quality Erosion Warning",
        one_line="Pages where engagement time is falling FASTER than traffic — the early-warning signal of content quality decay.",
        long_desc="Compares each page's engagement-time trend vs its traffic trend over the last 4 weeks. Flags pages where engagement is dropping at least 2× as fast as traffic — meaning the SAME number of people are visiting but spending less time. Could mean: content got stale, you're attracting lower-intent traffic, a competitor's snippet is stealing pre-click context, or a redesign hurt readability. This brief is rare in commercial tools because it requires comparing two trends per page — but it's the cleanest early-warning signal for content quality.",
        funnel="engagement",
        persona="raavi",
        is_new=True,
        complexity="advanced",
        roles=["content_marketer", "seo_lead", "editor"],
        metrics=["screenPageViews", "userEngagementDuration"],
        dimensions=["pagePath", "date"],
        collections=["content-intelligence", "wow-insights"],
        read_minutes=5,
    ),
    brief(
        id_="brief-ga-long-tail-discovery",
        name="Long-Tail Discovery",
        one_line="The pages with modest traffic + outstanding engagement. Hidden quality. Amplify these.",
        long_desc="Filters pages with 50-500 sessions in the period — too small to show on top-N reports, but big enough to mean something. Within that band, ranks by engagement time × conversion rate. The output is your 'should be bigger' list — content that's earned attention from the few people who found it and would likely earn attention from many more. Each row gets a tactical recommendation: 'add to nav', 'promote in email', 'build internal links from /blog/*', 'pitch as a paid-search target', 'turn into a video'.",
        funnel="engagement",
        persona="arjun",
        is_new=True,
        complexity="intermediate",
        roles=["content_marketer", "seo_lead", "growth_marketer"],
        metrics=["sessions", "userEngagementDuration", "conversionRate"],
        dimensions=["pagePath"],
        collections=["content-intelligence"],
        read_minutes=4,
    ),

    # ── Quick wins (3) ──────────────────────────────────────────────────────
    brief(
        id_="brief-ga-anomaly-scan",
        name="What Changed This Week",
        one_line="Automatic week-over-week anomaly scan across all your top metrics. The Monday-morning briefing in one screen.",
        long_desc="Compares every key metric (sessions, users, conversions, revenue, conversion rate, bounce rate, avg engagement) week-over-week. Flags any swing larger than 2 standard deviations. For each flagged metric, decomposes the change by dimension to surface the proximate cause: 'Conversions fell 22% — driven 80% by drop in Paid Search after Tuesday'.",
        funnel="acquisition",
        persona="raavi",
        is_popular=True,
        schedule="weekly",
        complexity="intermediate",
        metrics=["sessions", "totalUsers", "keyEvents", "totalRevenue"],
        dimensions=["date", "sessionDefaultChannelGroup"],
        collections=["weekly-rituals"],
    ),
    brief(
        id_="brief-ga-hidden-gems",
        name="Hidden Gems",
        one_line="Pages and sources with low traffic but exceptional conversion — quiet winners worth amplifying.",
        long_desc="Scores every page and every source on conversion-rate × log(sessions) — the combination that catches under-promoted high-value content. Anything with conversion rate > 2× site average + at least 50 sessions surfaces. Each row gets a recommendation: 'amplify with paid', 'add to nav', 'build internal links'.",
        funnel="conversion",
        persona="arjun",
        metrics=["sessions", "keyEvents", "conversionRate"],
        dimensions=["pagePath", "sessionDefaultChannelGroup"],
    ),
    brief(
        id_="brief-ga-monday-morning",
        name="Monday Morning Brief",
        one_line="The single executive summary: what moved, what to celebrate, what to investigate, what to expect.",
        long_desc="Composite weekly summary pulling from the channel mix, conversion trend, anomaly scan, and active-user series briefs. Outputs ~5 bullets: 1 win, 1 risk, 1 thing-to-investigate, 1 forecast for the coming week, 1 macro trend. Designed to be the first thing the CEO/marketing head reads on Monday at 9am — short, opinionated, sourced.",
        funnel="acquisition",
        persona="vera",
        is_popular=True,
        is_new=True,
        schedule="weekly",
        complexity="intermediate",
        metrics=["sessions", "keyEvents", "totalRevenue", "conversionRate"],
        dimensions=["sessionDefaultChannelGroup", "date"],
        collections=["weekly-rituals", "executive-briefs"],
        read_minutes=3,
    ),
]


def main():
    out = {"briefs": BRIEFS}
    path = "data/library/seed_briefs.json"
    with open(path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"wrote {len(BRIEFS)} briefs to {path}")
    # Audit funnel + persona distribution
    by_funnel = {}
    by_persona = {}
    for b in BRIEFS:
        by_funnel[b["funnel_stage"]] = by_funnel.get(b["funnel_stage"], 0) + 1
        by_persona[b["agent_persona"]] = by_persona.get(b["agent_persona"], 0) + 1
    print("funnel mix:", by_funnel)
    print("persona mix:", by_persona)


if __name__ == "__main__":
    main()
